{% set name = "botocore" %}
{% set version = "1.40.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boto/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ede9f34cbaaeabf3f1f3f4be004d6c75e713e1b45e6eb4f2a1f5cc387b92104f

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=71.1.0
    - wheel >=0.43.0
    - packaging
  run:
    - python
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27       # [py<310]
    - urllib3 >=1.25.4,!=2.2.0,<3  # [py>=310]
  run_constrained:
    - awscrt 0.23.8

# Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
# Error example:
#   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
#   - botocore.exceptions.ClientError: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
# Skipping integration tests:
{% set ignore_tests = " --ignore=tests/integration/" %}

# tests/functional/leak/test_resource_leaks.py:39: AssertionError
{% set ignore_tests_list = [] %}
{% set ignore_tests_list = ignore_tests_list + ["test_create_single_client_memory_constant"] %}     # [py==314 and osx]
{% set ignore_tests_list = ignore_tests_list + ["test_create_single_paginator_memory_constant"] %}  # [py==314 and osx]

test:
  source_files:
    - tests
  imports:
    - botocore
    - botocore.args
    - botocore.auth
    - botocore.awsrequest
    - botocore.client
    - botocore.compat
    - botocore.compress
    - botocore.config
    - botocore.configloader
    - botocore.configprovider
    - botocore.context
    - botocore.credentials
    - botocore.crt
    - botocore.discovery
    - botocore.docs
    - botocore.endpoint
    - botocore.endpoint_provider
    - botocore.errorfactory
    - botocore.eventstream
    - botocore.exceptions
    - botocore.handlers
    - botocore.history
    - botocore.hooks
    - botocore.httpchecksum
    - botocore.httpsession
    - botocore.loaders
    - botocore.model
    - botocore.monitoring
    - botocore.paginate
    - botocore.parsers
    - botocore.regions
    - botocore.response
    - botocore.retries
    - botocore.retries.base
    - botocore.retryhandler
    - botocore.serialize
    - botocore.session
    - botocore.signers
    - botocore.stub
    - botocore.tokens
    - botocore.translate
    - botocore.useragent
    - botocore.utils
    - botocore.validate
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
    - botocore.waiter
  commands:
    - pip check
    # Disabled win tests. It takes too much time—around 5 hours.
    # https://github.com/AnacondaRecipes/botocore-feedstock/pull/60#discussion_r1933937673
    - pytest -ra -v tests {{ ignore_tests }} -k "not slow{% if ignore_tests_list %} and not ({{ ignore_tests_list | join(' or ') }}){% endif %}"  # [not win]
  requires:
    - pip
    - pytest >=8.1.1
    - jsonschema >=4.23.0

about:
  home: https://aws.amazon.com/sdk-for-python
  license: Apache-2.0
  license_family: Apache
  license_file:
    - NOTICE
    - LICENSE.txt
    - tests/unit/auth/aws4_testsuite/LICENSE
    - tests/unit/auth/aws4_testsuite/NOTICE
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.amazonaws.com/v1/documentation/api/latest/index.html

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
    - ocefpaf
