{% set name = "botocore" %}
{% set version = "1.36.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boto/botocore/archive/{{ version }}.tar.gz
  sha256: 0cd84a46953ec7f44edffd0feee18bc652c2868338d80738c85ba4103ea7941e

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27       # [py<310]
    - urllib3 >=1.25.4,!=2.2.0,<3  # [py>=310]
  run_constrained:
    - awscrt 0.23.4

# Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
# Error example:
#   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
#   - botocore.exceptions.ClientError: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
# Skipping integration tests:
{% set ignore_tests = " --ignore=tests/integration/" %}

# RuntimeError: Unable to calculate correct timezone offset for "0"
{% set tests_to_skip = "test_parse_timestamp_succeeds_with_fromtimestamp_oserror" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_parse_timestamp_succeeds_with_fromtimestamp_overflowerror" %}  # [win]

# RuntimeError: Unable to calculate correct timezone offset for "-2208988800"
{% set tests_to_skip = tests_to_skip + " or test_parse_epoch_negative_time" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - botocore
    - botocore.docs
    - botocore.docs.bcdoc
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
  commands:
    - pip check
    - pytest -v {{ ignore_tests }} tests  # [not win]
    # Disabled win tests. It takes too much time—around 5 hours.
    # https://github.com/AnacondaRecipes/botocore-feedstock/pull/60#discussion_r1933937673
    # - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" tests  # [win]
  requires:
    - pip
    - pytest
    - jsonschema

about:
  home: https://aws.amazon.com/sdk-for-python/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - NOTICE
    - LICENSE.txt
    - tests/unit/auth/aws4_testsuite/LICENSE
    - tests/unit/auth/aws4_testsuite/NOTICE
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.amazonaws.com/v1/documentation/api/latest/index.html

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
    - ocefpaf
