{% set name = "botocore" %}
{% set version = "1.29.120" %}
{% set hash = "82de714c06fcefbcf2f3854b81c51bf0c529ec902c6e927156ff47988aaeeb7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/botocore-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv

#test
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jmespath >=0.7.1,<2.0.0
    - python-dateutil >=2.1,<3.0.0
    - urllib3 >=1.25.4,<1.27

test:
  imports:
    - botocore
    - botocore.docs
    - botocore.docs.bcdoc
    - botocore.vendored
    - botocore.vendored.requests
    - botocore.vendored.requests.packages
    - botocore.vendored.requests.packages.urllib3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://aws.amazon.com/sdk-for-python/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Low-level, data-driven core of boto 3.
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  dev_url: https://github.com/boto/botocore
  doc_url: https://botocore.amazonaws.com/v1/documentation/api/latest/index.html

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
    - ocefpaf
